import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/mainPage/sidebar";
import "./globals.css";
import StoreProvider from "./storeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div style={{ display: "flex", height: "100vh" }}>
            <Sidebar />
            <div style={{ flex: 1 }}>{children}</div> 
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}